[package]
name = "efr"
version = "0.1.0"
edition = "2024"
description = "efr (EFile Rust)"
license = "MIT"
repository = "https://github.com/williamcparks/efr"
readme = "README.md"
keywords = ["efr"]

[features]
metadata = []

[dependencies]
base64 = "0.22.1"
chrono = { version = "0.4.43", features = ["serde"] }
efr-macros = { version = "0.1.0", path = "../efr-macros" }
quick-xml = { version = "0.39.2", features = ["serialize"] }
rsa = { version = "0.9.10", features = ["sha1"] }
serde = { version = "1.0.228", features = ["derive"] }
sha1 = "0.10.6"
thiserror = "2.0.18"
uuid = { version = "1.21.0", features = ["v4"] }
